"""Static HTML exporter for the shared index.

No external CSS/JS - everything inlined so the report can be emailed or
attached to a ticket. Output is deterministic and PII-redacted (the redacted
secret fingerprints are what we render, never raw values).
"""

from __future__ import annotations

import html
import json
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from ..core.index import Index


SEVERITY_COLOR = {
    "critical": "#7a1f1f",
    "high": "#a23a1d",
    "medium": "#a07a1d",
    "low": "#3d6b3d",
    "info": "#395a7a",
}


CSS = """
:root { color-scheme: light dark; }
body { font: 14px/1.45 ui-sans-serif, system-ui, sans-serif; margin: 0; padding: 24px; }
h1 { margin: 0 0 6px; font-size: 22px; }
h2 { margin: 24px 0 8px; font-size: 16px; border-bottom: 1px solid #8884; padding-bottom: 4px; }
.badge { display: inline-block; padding: 1px 8px; border-radius: 999px; color: #fff; font-size: 12px; }
.meta { color: #666; font-size: 12px; }
table { border-collapse: collapse; width: 100%; margin-top: 8px; }
th, td { text-align: left; padding: 6px 8px; vertical-align: top; }
tr:nth-child(odd) td { background: #8881; }
code { background: #8882; padding: 1px 4px; border-radius: 3px; }
.kv { font-family: ui-monospace, monospace; font-size: 12px; }
.foot { margin-top: 24px; color: #888; font-size: 12px; }
"""


def render(index: Index, out: Path, title: str = "Aegis report") -> Path:
    rows = list(index.findings())
    stats = index.stats()
    parts: list[str] = []
    parts.append("<!doctype html><html><head><meta charset=\"utf-8\">")
    parts.append(f"<title>{html.escape(title)}</title><style>{CSS}</style></head><body>")
    parts.append(f"<h1>{html.escape(title)}</h1>")
    parts.append(
        f"<div class=\"meta\">files indexed: {stats['files']} &middot; "
        f"findings: {stats['findings']}</div>"
    )

    parts.append("<h2>By severity</h2><table><tr><th>Severity</th><th>Count</th></tr>")
    for sev in ("critical", "high", "medium", "low", "info"):
        n = stats["by_severity"].get(sev, 0)
        if not n:
            continue
        color = SEVERITY_COLOR.get(sev, "#444")
        parts.append(
            f"<tr><td><span class=\"badge\" style=\"background:{color}\">"
            f"{html.escape(sev)}</span></td><td>{n}</td></tr>"
        )
    parts.append("</table>")

    parts.append("<h2>Findings</h2><table>")
    parts.append("<tr><th>Severity</th><th>Scanner / rule</th><th>Path</th><th>Details</th></tr>")
    for r in rows:
        sev = r.get("severity", "info")
        color = SEVERITY_COLOR.get(sev, "#444")
        details = r.get("details") or {}
        loc = f":{r['line']}" if r.get("line") else ""
        details_str = html.escape(json.dumps(details, indent=2, default=str))
        parts.append(
            "<tr>"
            f"<td><span class=\"badge\" style=\"background:{color}\">{html.escape(sev)}</span></td>"
            f"<td>{html.escape(r.get('scanner',''))}/{html.escape(r.get('rule',''))}</td>"
            f"<td><code>{html.escape(r.get('path',''))}{html.escape(loc)}</code></td>"
            f"<td><pre class=\"kv\">{details_str}</pre></td>"
            "</tr>"
        )
    parts.append("</table>")
    parts.append("<div class=\"foot\">Generated by Aegis. Charter-bound, locally produced.</div>")
    parts.append("</body></html>")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("".join(parts), encoding="utf-8")
    return out
